name: Create Bio Page

on:
  issues:
    types: [opened, labeled]

jobs:
  create-bio:
    if: contains(github.event.issue.labels.*.name, 'bio-creation')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Extract bio information
        id: extract
        uses: actions/github-script@v7
        with:
          script: |
            const issueBody = context.payload.issue.body;
            
            // Function to extract value after a header
            function extractValue(header) {
              const regex = new RegExp(`### ${header}\\n(.+?)(?=\\n###|$)`, 's');
              const match = issueBody.match(regex);
              return match ? match[1].trim() : '';
            }
            
            // Extract values
            const username = extractValue('Username');
            const displayName = extractValue('Display Name');
            const pronouns = extractValue('Pronouns');
            const bio = extractValue('Bio');
            const links = extractValue('Website Links');
            
            // Log to check if we are getting the correct values
            console.log("Username:", username);
            console.log("Display Name:", displayName);
            console.log("Pronouns:", pronouns);
            console.log("Bio:", bio);
            console.log("Links:", links);
            
            // Validate username
            if (!username) {
              core.setFailed('Username is required');
              return;
            }
            
            // Export variables to be used in the next steps
            core.exportVariable('USERNAME', username);
            core.exportVariable('DISPLAY_NAME', displayName);
            core.exportVariable('PRONOUNS', pronouns);
            core.exportVariable('BIO', bio);
            core.exportVariable('LINKS', links);

      - name: Create bio file
        run: |
          mkdir -p src/content/bios
          # Use printf to properly handle multiline content
          printf "---\nusername: \"$USERNAME\"\ndisplay_name: \"$DISPLAY_NAME\"\npronouns: \"$PRONOUNS\"\nbio: |\n  $BIO\nlinks: |\n  $LINKS\n---" > src/content/bios/$USERNAME.md
          
          # Debug output to verify the file creation
          cat src/content/bios/$USERNAME.md

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add src/content/bios/$USERNAME.md
          git commit -m "Add bio for @$USERNAME" || echo "No changes to commit"
          git push

      - name: Close issue with comment
        uses: actions/github-script@v7
        with:
          script: |
            const username = process.env.USERNAME;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `✨ Your bio page has been created! View it at [blahaj.bio/@${username}](https://blahaj.bio/@${username})`
            });

            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              state: 'closed'
            });