name: Create Bio Page

on:
  issues:
    types: [closed, opened, labeled]

jobs:
  create-bio:
    if: contains(github.event.issue.labels.*.name, 'bio-creation')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Extract bio information
        id: extract
        uses: actions/github-script@v7
        with:
          script: |
            const issueBody = context.payload.issue.body;
            
            // Directly extract data based on markdown headers
            const username = issueBody.split('### Username')[1]?.split('\n')[1]?.trim() || '';
            const displayName = issueBody.split('### Display Name')[1]?.split('\n')[1]?.trim() || '';
            const pronouns = issueBody.split('### Pronouns')[1]?.split('\n')[1]?.trim() || '';
            const bio = issueBody.split('### Bio')[1]?.split('\n')[1]?.trim() || '';
            const links = issueBody.split('### Website Links')[1]?.split('\n')[1]?.trim() || '';
            
            // Log to check if we are getting the correct values
            console.log("Username:", username);
            console.log("Display Name:", displayName);
            console.log("Pronouns:", pronouns);
            console.log("Bio:", bio);
            console.log("Links:", links);
            
            // Export variables to be used in the next steps
            core.exportVariable('USERNAME', username);
            core.exportVariable('DISPLAY_NAME', displayName);
            core.exportVariable('PRONOUNS', pronouns);
            core.exportVariable('BIO', bio);
            core.exportVariable('LINKS', links);

      - name: Create bio file
        run: |
          mkdir -p src/content/bios
          cat > src/content/bios/${{ env.USERNAME }}.md <<EOF
          ---
          username: "${{ env.USERNAME }}"
          display_name: "${{ env.DISPLAY_NAME }}"
          pronouns: "${{ env.PRONOUNS }}"
          bio: |
            ${{ env.BIO }}
          links: |
            ${{ env.LINKS }}
          ---
          EOF
          # Debug output to verify the file creation
          cat src/content/bios/${{ env.USERNAME }}.md

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add src/content/bios/${{ env.USERNAME }}.md
          git commit -m "Add bio for @${{ env.USERNAME }}" || echo "No changes to commit"
          git push

      - name: Close issue with comment
        uses: actions/github-script@v7
        with:
          script: |
            const username = process.env.USERNAME;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `✨ Your bio page has been created! View it at [blahaj.bio/@${username}](https://blahaj.bio/@${username})`
            });

            await github.rest.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              state: 'closed'
            });