name: Create Bio Page
on:
  issues:
    types: [opened, labeled]
jobs:
  create-bio:
    if: contains(github.event.issue.labels.*.name, 'bio-creation')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Extract bio information
        id: extract
        uses: actions/github-script@v7
        with:
          script: |
            const issueBody = context.payload.issue.body;
            // Directly extract data based on markdown headers
            const username = issueBody.split('### Username')[1]?.split('\n')[1]?.trim() || '';
            const displayName = issueBody.split('### Display Name')[1]?.split('\n')[1]?.trim() || '';
            const pronouns = issueBody.split('### Pronouns')[1]?.split('\n')[1]?.trim() || '';
            const bio = issueBody.split('### Bio')[1]?.split('\n')[1]?.trim() || '';
            const links = issueBody.split('### Website Links')[1]?.split('\n')[1]?.trim() || '';
            // Log to check if we are getting the correct values
            console.log("Username:", username);
            console.log("Display Name:", displayName);
            console.log("Pronouns:", pronouns);
            console.log("Bio:", bio);
            console.log("Links:", links);
            // Export variables to be used in the next steps
            core.exportVariable('USERNAME', username);
            core.exportVariable('DISPLAY_NAME', displayName);
            core.exportVariable('PRONOUNS', pronouns);
            core.exportVariable('BIO', bio);
            core.exportVariable('LINKS', links);

      - name: Create bio file
        run: |
          mkdir -p src/content/bios
          echo -e "---\nusername: \"${{ env.USERNAME }}\"\ndisplay_name: \"${{ env.DISPLAY_NAME }}\"\npronouns: \"${{ env.PRONOUNS }}\"\nbio: |\n  ${{ env.BIO }}\nlinks: |\n  ${{ env.LINKS }}\n---" > src/content/bios/${{ env.USERNAME }}.md
